### ISSUE TITLE
Publish the build output in an other branch

### ISSUE THREAD

**Issue by dolmen** [mrkline/concurrency-primer#2]
It would be helpful if you would publish a PDF of the output. To not pollute the master branch where you keep the sources you could publish that build output in another branch on this repository.

**Comment by mrkline** [comment]
Hey, sorry for the delayed response! Along with always placing the latest version at <https://assets.bitbashing.io/papers/lockless.pdf>, would it be alright if I posted rendered copies as "releases" for the tagged versions on Github and Gitlab?

**Comment by dolmen** [comment]
Well, as the PDF is in fact already available, the only missing bit is to advertise it in README.

**Comment by mrkline** [comment]
Done with 3e3c1f952dcb740f63cb59219a04671840ce570a. Thanks!
